-- Name:Xiaoxiao Cao,ID:103043833,Name:Sariya Tusa,ID:
-- /////////////Task1.1///////////////////////////////////////////////
SELECT name 
from sys.databases;
-- create database DW3833
use DW3833
CREATE TABLE ERROREVENT (
ERRORID INTEGER,
SOURCE_ID NVARCHAR(50),
SOURCE_TABLE NVARCHAR(50),
FILTERID INTEGER,
DATETIME DATETIME,
ACTION NVARCHAR(50),
CONSTRAINT ERROREVENTACTION CHECK (ACTION IN ('SKIP','MODIFY'))
);
-- ///////////////////////Task1.2/////////////////////////////////////
IF OBJECT_ID('DWPROD') IS NOT NULL
DROP TABLE DWPROD;
IF OBJECT_ID('DWCUST') IS NOT NULL
DROP TABLE DWCUST;
IF OBJECT_ID('DWSALE') IS NOT NULL
DROP TABLE DWSALE;
-- use TPS
-- SELECT table_catalog[database],table_schema [schema],table_name name,table_type type
-- FROM INFORMATION_SCHEMA.TABLES
-- GO
-- SELECT * 
-- FROM PRODUCT
-- SELECT *
-- FROM PRODCATEGORY
-- SELECT *
-- FROM MANUFACTURER
-- SELECT *
-- FROM SHIPPING
-- SELECT *
-- FROM SALEMELB

-- use DW3833
CREATE TABLE DWPROD(
    DWPRODID INT IDENTITY(1,1),  
    DWSOURCETABLE NVARCHAR(10) DEFAULT 'PRODUCT', 
    DWSOURCEID INT NOT NULL, 
    PRODNAME NVARCHAR(50),
    PRODCATNAME NVARCHAR(50),
    PRODMANUNAME NVARCHAR(50), 
    PRODSHIPNAME NVARCHAR(50),
    PRIMARY KEY (DWPRODID)
);
 CREATE TABLE DWCUST (
     DWCUSTID,
  DWSOURCEIDBRIS,
   DWSOURCEIDMELB, 
   FIRSTNAME, 
   SURNAME, 
   GENDER,
PHONE,
 POSTCODE, 
 CITY, 
 STATE, 
 CUSTCATNAME)
